@url_dev = http://localhost:8000/v1/api/

### signup
POST {{url_dev}}/shop/signup
Content-Type: application/json
x-api-key: sdfjs;dafjsdfj

{
    "name": "viettu1",
    "email": "viettu1@gmail.com`",
    "password": "viettu1"
}